### ISSUE TITLE
BUG: condição `if` incompleta na inicialização da variável `install_requires` 

### ISSUE THREAD

**Issue by camaramm** [petrobras/BibMon#11]
Se a condição _if_ a seguir não for satisfeita:
https://github.com/petrobras/BibMon/blob/7f2202bcfa1d0ef7aeea17dabe6e87ddabc37338/setup.py#L17-L19
a variável `install_requires` não será inicializada e causará exceção na linha:
https://github.com/petrobras/BibMon/blob/7f2202bcfa1d0ef7aeea17dabe6e87ddabc37338/setup.py#L37

Uma possibilidade de solução seria incluir o `else` para inicializar a variável `install_requires` para um valor padrão.

**Comment by yelken** [comment]
https://github.com/petrobras/BibMon/pull/22

**Comment by afraniomelo** [comment]
Closing this issue. Thank you for contribution, @yelken !
