### ISSUE TITLE
Falha no job para submissão no repositório conda-forge

### ISSUE THREAD

**Issue by camaramm** [petrobras/BibMon#9]
Olá @afraniomelo .

Submeti a BibMon no repositório conda-forge ([PR](https://github.com/conda-forge/staged-recipes/pull/26457)) para que o pacote possa ser instalado e gerenciado também com o `conda`.

Porém, surgiu um erro nos processos de build `NameError: name 'install_requires' is not defined` que entendi estar relacionado a um comando no setup.py:

https://github.com/petrobras/BibMon/blob/7f2202bcfa1d0ef7aeea17dabe6e87ddabc37338/setup.py#L37

conforme você pode conferir no log de um dos jobs: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=942464&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=724

Alguma suspeita sobre a possível causa desse erro?

**Comment by afraniomelo** [comment]
Oi, @camaramm. Muito obrigado pela submissão da BibMon no repositório conda-forge. Para fazer funcionar, foi necessário adicionar explicitamente o arquivo `requirements.txt` no tarball enviado ao PyPI, como especificado no arquivo `MANIFEST.in`. Como o problema foi resolvido e você conseguiu efetuar a publicação no `conda-forge`, estou encerrando esta issue.

**Comment by camaramm** [comment]
De acordo, @afraniomelo. Mais informações podem ser obtidas diretamente no PR https://github.com/conda-forge/staged-recipes/pull/27400.
